from typing import Self

class Progress:
    def __init__(self: Self) -> None: ...
    def start(self: Self, name: str, estimated_total_items: int) -> Self: ...
    def increase_estimate(self: Self, count: int) -> None: ...
    def end(self: Self) -> None: ...
    def completeOne(self: Self) -> None: ...
