// Validates fourt2py/wasm/fourt.c (compiled to wasm by `npm run build:wasm`,
// a manual/optional step -- `npm test` no longer builds it, so CI needs no
// emcc) against fixtures captured from the authoritative Python/f2py binding
// of the original FOURT.F (see fourt2py/wasm/fixtures.json, regenerated by
// fourt2py/wasm/generate_fixtures.py). This is the independent check that
// the wasm build behaves identically to the real Fortran, not just that the
// C port is internally consistent. Cases cover both iform=1 (ICASE=1, the
// complex transform the demo uses) and iform=0 (ICASE=3/4, the real-array
// path fourt.c also implements but the demo doesn't call).
//
// Skipped whenever wasm/fourt.mjs hasn't been built: run
// `npm run build:wasm` first to opt in.
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { beforeAll, describe, expect, test } from 'vitest';
import { Fourt } from '../fourt.mjs';

const wasmMjsUrl = new URL('../../wasm/fourt.mjs', import.meta.url);
const fixtures = JSON.parse(readFileSync(new URL('../../wasm/fixtures.json', import.meta.url), 'utf8'));

describe.skipIf(!existsSync(fileURLToPath(wasmMjsUrl)))('Fourt (wasm build of fourt2py/wasm/fourt.c)', () => {
    let fourt;

    beforeAll(async () => {
        fourt = await Fourt.instantiate(wasmMjsUrl);
    });

    test.each(fixtures.cases)('n=$n isign=$isign iform=$iform matches the Fortran oracle', (fixture) => {
        const data = Float64Array.from(fixture.input);
        const got = fourt.transform(data, fixture.n, { isign: fixture.isign, iform: fixture.iform });
        for (let i = 0; i < got.length; i++) {
            const tolerance = fixtures.tolerance.atol + fixtures.tolerance.rtol * Math.abs(fixture.expected[i]);
            expect(Math.abs(got[i] - fixture.expected[i])).toBeLessThanOrEqual(tolerance);
        }
    });
});

