// Validates fourt2py/wasm/fourt.c (compiled to wasm by `npm run build`)
// against fixtures captured from the authoritative Python/f2py binding of
// the original FOURT.F (see fourt2py/wasm/fixtures.json, regenerated by
// fourt2py/wasm/generate_fixtures.py). This is the independent check that
// the wasm build behaves identically to the real Fortran, not just that the
// C port is internally consistent. Cases cover both iform=1 (ICASE=1, the
// complex transform the demo uses) and iform=0 (ICASE=3/4, the real-array
// path fourt.c also implements but the demo doesn't call).
import { readFile } from 'node:fs/promises';
import { describe, expect, test } from 'vitest';
import { Fourt } from '../fourt.mjs';

const fixtures = JSON.parse(await readFile(new URL('../../wasm/fixtures.json', import.meta.url), 'utf8'));
const fourt = await Fourt.instantiate(new URL('../../wasm/fourt.mjs', import.meta.url));

describe('Fourt (wasm build of fourt2py/wasm/fourt.c)', () => {
    test.each(fixtures.cases)('n=$n isign=$isign iform=$iform matches the Fortran oracle', (fixture) => {
        const data = Float64Array.from(fixture.input);
        const got = fourt.transform(data, fixture.n, { isign: fixture.isign, iform: fixture.iform });
        for (let i = 0; i < got.length; i++) {
            const tolerance = fixtures.tolerance.atol + fixtures.tolerance.rtol * Math.abs(fixture.expected[i]);
            expect(Math.abs(got[i] - fixture.expected[i])).toBeLessThanOrEqual(tolerance);
        }
    });
});
